### ISSUE TITLE
Deploy on Production environments

### ISSUE THREAD

**Issue by rdrgporto** [metal-stack/csi-lvm#26]
Hi,

I have been working with this **CSI** over a week. I have some questions:

1. **Docker image** is not stored in any **public registry** ?
2. The location **/tmp/csi-lvm** could be changed ? For example: **/var/lib/csi-lvm ? Because **/tmp** is erased after a **reboot**.

I have attached a **new disk** on my virtual machine (**/dev/sdb**) and I replaced it for **/dev/loop[0,1]** on **CSI LVM Controller**.

```
 - name: CSI_LVM_DEVICE_PATTERN
   value: "/dev/sdb1"
```

I have deployed **controller**, **reviver**, **pvc** and **pod**. It worked, however after rebooting the virtual machine, data was erased.

I would like to know the steps that I need in order to deploy this tool on **production** environments.

Thanks in advance,

Regards

**Comment by majst01** [comment]
Hi,

1. Docker images are here:
https://hub.docker.com/r/metalstack/csi-lvm-controller
https://hub.docker.com/r/metalstack/csi-lvm-provisioner
2. This is by design, after reboot the reviver pod will remount all PVs as before. You cant rely on stuff installed/configured on the machine on a kubernetes node because this might always be gone. kubelet reconcilation must take care.

Please give more details like:
- k8s version
- csi-lvm version
- your manifests you deployed csi-lvm

**Comment by rdrgporto** [comment]
Hi @majst01,

- **k8s version**: 1.15.4
- **csi-lvm**: 0.6.0

I have seen that **0.6.1** is not available on **Docker Hub**. I have modified manifests in order to use **0.6.0** version.

As I said above, I have attached a new disk (**/dev/sdb**) and I had to create a **Physical Volume** and **Volume Group**:

```
sudo pvcreate /dev/sdb1
sudo vgcreate csi-lvm /dev/sdb1
```

It is neccesary to do that ?

I have modified **controller deployment manifest** in order to use **/dev/sdb1**:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-lvm-controller
  namespace: csi-lvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-lvm-controller
  template:
    metadata:
      labels:
        app: csi-lvm-controller
    spec:
      serviceAccountName: csi-lvm-controller
      containers:
      - name: csi-lvm-controller
        image: metalstack/csi-lvm-controller:v0.6.0
        imagePullPolicy: IfNotPresent
        command:
        - /csi-lvm-controller
        args:
        - start
        env:
        - name: CSI_LVM_PROVISIONER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CSI_LVM_PULL_POLICY
          value: "IfNotPresent"
        - name: CSI_LVM_PROVISIONER_IMAGE
          value: "metalstack/csi-lvm-provisioner:v0.6.0"
        - name: CSI_LVM_DEVICE_PATTERN
          value: "/dev/sdb1"
```

Finally, I have deployed a **Statefulset** example:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: local-test
spec:
  serviceName: "local-service"
  replicas: 2
  selector:
    matchLabels:
      app: local-test-new
  template:
    metadata:
      labels:
        app: local-test-new
    spec:
      containers:
      - name: test-container
        image: k8s.gcr.io/busybox
        command:
        - "/bin/sh"
        args:
        - "-c"
        - "count=0; count_file=\"/usr/test-pod/count\"; test_file=\"/usr/test-pod/test_file\"; if [ -e $count_file ]; then count=$(cat $count_file); fi; echo $((count+1)) > $count_file; while [ 1 ]; do date >> $test_file; echo \"This is $MY_POD_NAME, count=$(cat $count_file)\" >> $test_file; sleep 10; done"
        volumeMounts:
        - name: local-vol
          mountPath: /usr/test-pod
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      securityContext:
        fsGroup: 1234
  volumeClaimTemplates:
  - metadata:
      name: local-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "csi-lvm"
      resources:
        requests:
          storage: 1Gi
```

It created **pv**, **pvc** and **pods** correctly. After rebooting, **csi-lvm-reviver** created **pvc** in **/tmp/csi-lvm** again, so that, it worked.

Perphaps, the last time, I did something wrong or I did not have enough patience.

Thanks,

Regards
