### ISSUE TITLE
Support multiple volume groups via storage classes

### ISSUE THREAD

**Issue by theduke** [metal-stack/csi-lvm#38]
Thanks for this project, very useful!

At the moment, the used disks are hardcoded via a env var in the controller.

This is a somewhat limiting design. 
Concretely, I need support for two separate volume groups. (fast (SSDs) and slow (HDDs))

Proposed design: the `StorageClass` contains all necessary  mapping in parameters.

The disks shouldn't need to be hardcoded at all by default. 

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-arbitrary-name
params:
  volumeGroup: fast-disks
  # Purely optional, for restricting:
  disks: ["sdc", "sde"]
provisioner: metal-stack.io/csi-lvm
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
```
